import { Project } from '../entities/Project';

export type ExportFormat = 'json' | 'markdown' | 'plain' | 'copilot' | 'claude' | 'cursor';

export function exportProject(project: Project, format: ExportFormat): string {
  switch (format) {
    case 'json': return exportJSON(project);
    case 'markdown': return exportMarkdown(project);
    case 'plain': return exportPlain(project);
    case 'copilot': return exportCopilot(project);
    case 'claude': return exportClaude(project);
    case 'cursor': return exportCursor(project);
  }
}

/** Target file path for AI tool config formats */
export function getExportFilename(format: ExportFormat, projectName: string): string {
  const slug = projectName.toLowerCase().replace(/\s+/g, '-');
  switch (format) {
    case 'json': return `${slug}-context.json`;
    case 'markdown': return `${slug}-context.md`;
    case 'plain': return `${slug}-context.txt`;
    case 'copilot': return '.github/copilot-instructions.md';
    case 'claude': return 'CLAUDE.md';
    case 'cursor': return '.cursorrules';
  }
}

function formatEntries(entries: any[]): Record<string, any[]> {
  const grouped: Record<string, any[]> = {};
  for (const e of entries || []) {
    if (!grouped[e.category]) grouped[e.category] = [];
    grouped[e.category].push(e);
  }
  return grouped;
}

// --- JSON ---
function exportJSON(project: Project): string {
  return JSON.stringify({
    project: { id: project.id, name: project.name, description: project.description },
    contexts: (project.contextEntries || []).map(e => ({
      key: e.key, value: e.value, category: e.category, priority: e.priority, metadata: e.metadata,
    })),
    decisions: (project.decisions || []).map(d => ({
      title: d.title, description: d.description, rationale: d.rationale, status: d.status, alternatives: d.alternatives,
    })),
    exportedAt: new Date().toISOString(),
  }, null, 2);
}

// --- Markdown ---
function exportMarkdown(project: Project): string {
  const lines: string[] = [`# ${project.name}`];
  if (project.description) lines.push('', project.description);

  const grouped = formatEntries(project.contextEntries);
  if (Object.keys(grouped).length > 0) {
    lines.push('', '## Context & Architecture', '');
    for (const [category, entries] of Object.entries(grouped)) {
      lines.push(`### ${category.charAt(0).toUpperCase() + category.slice(1)}`, '');
      for (const e of entries) {
        lines.push(`**${e.key}** (priority: ${e.priority})`);
        lines.push('', e.value, '');
      }
    }
  }

  if (project.decisions?.length) {
    lines.push('## Architectural Decisions', '');
    for (const d of project.decisions) {
      lines.push(`### ${d.title}`, '');
      lines.push(`**Status:** ${d.status}`, '');
      lines.push(d.description, '');
      if (d.rationale) lines.push(`**Rationale:** ${JSON.stringify(d.rationale)}`, '');
    }
  }

  return lines.join('\n');
}

// --- Plain text ---
function exportPlain(project: Project): string {
  const lines: string[] = [
    project.name.toUpperCase(),
    '='.repeat(project.name.length),
  ];
  if (project.description) lines.push('', project.description);

  if (project.contextEntries?.length) {
    lines.push('', 'CONTEXT ENTRIES:', '-'.repeat(50));
    for (const e of project.contextEntries) {
      lines.push('', `[${e.category}] ${e.key} (Priority: ${e.priority})`, e.value);
    }
  }

  if (project.decisions?.length) {
    lines.push('', '', 'ARCHITECTURAL DECISIONS:', '-'.repeat(50));
    for (const d of project.decisions) {
      lines.push('', `${d.title} [${d.status}]`, d.description);
    }
  }

  return lines.join('\n');
}

// --- GitHub Copilot (.github/copilot-instructions.md) ---
function exportCopilot(project: Project): string {
  const lines: string[] = [
    `# Copilot Instructions - ${project.name}`,
    '',
    `> Auto-generated by ThinkBrew. Last updated: ${new Date().toISOString()}`,
    '',
  ];

  if (project.description) lines.push(project.description, '');

  const grouped = formatEntries(project.contextEntries);
  const order = ['architecture', 'standards', 'requirements', 'dependencies', 'general'];
  for (const cat of order) {
    const entries = grouped[cat];
    if (!entries?.length) continue;
    lines.push(`## ${cat.charAt(0).toUpperCase() + cat.slice(1)}`, '');
    for (const e of entries) {
      lines.push(`- **${e.key}**: ${e.value}`);
    }
    lines.push('');
  }

  if (project.decisions?.length) {
    lines.push('## Key Decisions', '');
    for (const d of project.decisions.filter(d => d.status === 'active')) {
      lines.push(`- **${d.title}**: ${d.description}`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

// --- Claude (CLAUDE.md) ---
function exportClaude(project: Project): string {
  const lines: string[] = [
    `# ${project.name}`,
    '',
    `> Auto-generated by ThinkBrew. Last updated: ${new Date().toISOString()}`,
    '',
  ];

  if (project.description) lines.push(project.description, '');

  const grouped = formatEntries(project.contextEntries);
  const order = ['architecture', 'standards', 'requirements', 'dependencies', 'general'];
  for (const cat of order) {
    const entries = grouped[cat];
    if (!entries?.length) continue;
    lines.push(`## ${cat.charAt(0).toUpperCase() + cat.slice(1)}`, '');
    for (const e of entries) {
      lines.push(`### ${e.key}`, '', e.value, '');
    }
  }

  if (project.decisions?.length) {
    lines.push('## Architectural Decisions', '');
    for (const d of project.decisions) {
      lines.push(`### ${d.title} [${d.status}]`, '', d.description, '');
      if (d.rationale) {
        lines.push('**Rationale:**', '', JSON.stringify(d.rationale, null, 2), '');
      }
    }
  }

  return lines.join('\n');
}

// --- Cursor (.cursorrules) ---
function exportCursor(project: Project): string {
  const lines: string[] = [
    `# ${project.name} - Cursor Rules`,
    '',
    `# Auto-generated by ThinkBrew. Last updated: ${new Date().toISOString()}`,
    '',
  ];

  if (project.description) lines.push(project.description, '');

  const grouped = formatEntries(project.contextEntries);
  if (grouped['standards']?.length) {
    lines.push('## Coding Standards', '');
    for (const e of grouped['standards']) {
      lines.push(`- ${e.key}: ${e.value}`);
    }
    lines.push('');
  }
  if (grouped['architecture']?.length) {
    lines.push('## Architecture', '');
    for (const e of grouped['architecture']) {
      lines.push(`- ${e.key}: ${e.value}`);
    }
    lines.push('');
  }
  for (const cat of ['requirements', 'dependencies', 'general']) {
    const entries = grouped[cat];
    if (!entries?.length) continue;
    lines.push(`## ${cat.charAt(0).toUpperCase() + cat.slice(1)}`, '');
    for (const e of entries) {
      lines.push(`- ${e.key}: ${e.value}`);
    }
    lines.push('');
  }

  if (project.decisions?.length) {
    lines.push('## Decisions', '');
    for (const d of project.decisions.filter(d => d.status === 'active')) {
      lines.push(`- ${d.title}: ${d.description}`);
    }
    lines.push('');
  }

  return lines.join('\n');
}
